# versionは、3系
version: "3"
# Serviceを設定する
services:
  # Service名は、自由に決めていい
  frontend:
    # DockerfileまでのPath
    build: .
    # 環境変数を定義する
    environment:
      # Node.jsのグローバル変数: 開発用途なのでdevelopmentを指定
      - NODE_ENV=development
    # ホストマシン:コンテナ => ファイルを共有するための設定
    volumes:
      - ./:/usr/src/app
    # Dockerコンテナ内で実行されるコマンドを指定する
    command: sh -c 'cd frontend && yarn start'
    # ホストマシンPort番号:コンテナのPost番号
    ports:
      - 8000:3000
    # CLI画面の操作をできるようにする
    tty: true
